### ISSUE TITLE
Still working on this?

### ISSUE THREAD

**Issue by turbodog** [mitchpond/Spotify-HE-Connect#1]
Hi Mitch,

Viewing Spotify now playing and controls is of interest to me too. Are you still working on this or had success getting it to work? I installed the dev branch code on my ST hub and it appears in the ST app dashboard but doesn't seem to be interacting with Spotify. Happy to help contribute and test if necessary.

thanks

**Comment by mitchpond** [comment]
Yes, I am. On and off. I may not have pushed the latest changes to Github. The code I have in HE has been happily refreshing my API key and working for the past few months. It's also working nicely with Rule Machine to start a playlist when getting home from work. 
I was hoping that Hubitat would have implemented the cloud-based OAuth redirect. It seemed implied that it was on the roadmap, but no word yet (https://community.hubitat.com/t/oauth-questions). It's a bit janky without that and I didn't want to actually release anything until it was up to par.

**Comment by rvrolyk** [comment]
Hi Mitch,
any chance you'd be up for publishing your latest copy?  I can't tell if HE is planning on adding support for the OAuth redirect anytime soon but I don't mind hacking my way around that issue.  It's far better than the super flaky solution I'm using now....

**Comment by mitchpond** [comment]
Sorry for the delayed response. I've been fighting a nasty bug (not the coding type) this week, so my motivation to do much outside of work has been approximately zero. I'll see about cleaning up and committing something either this weekend or at some time next week.

**Comment by rvrolyk** [comment]
No worries Mitch, something has been going around the office here too.
Hope you're feeling better soon.

>

**Comment by turbodog** [comment]
Mitch I'd be grateful if you could help troubleshoot my issue getting the app to auth successfully. What I've done:
- Installed the dev branches of device and smart app into the ST IDE
- Created my own app in Spotify
- Pasted in the client ID and client secret from Spotify into the app code
- Uncommented every log statement
- In the Spotify app set redirect URI to "https://graph.api.smartthings.com/oauth/callback"
- In the ST classic app under SmartApps / Automation, click Manage Spotify permissions then Spotify Connect 
- This prompts for login to Spotify, which succeeds
- This prompts for login to ST account. The login appears to succeed but
- I get "Oh no something went wrong"
-- Error: 500
-- URI: /oath/callback
-- Logs
> No authToken yet, sending user to Spotify...
> No authToken yet, sending user to Spotify...
> Entered OAuth init... 
> Sending oAuth state of: 2e2b211c-3d8e-4bcb-bd34-bc934b838b74
> Entered OAuth init...
> Sending oAuth state of: 2e2b211c-3d8e-4bcb-bd34-bc934b838b74
- No further output from logs
- Watching the logs stream in, it appears that all the output above happens before I attempt to login to Spotify

**Comment by rvrolyk** [comment]
Hi Mitch,

I was just wondering if you'd had any luck getting to this as it looks like
the last commit was still 6 months ago.

thanks!

>

**Comment by mitchpond** [comment]
I'm still alive and the project is as well. 

I'm going to rework/rewrite the OAuth flow since it doesn't look like Hubitat will be implementing a proper cloud OAuth redirect any time soon. I waited for much too long hoping to eliminate the need for the user to screw around with manually copying and pasting tokens and URLs, as well as the need for their own Spotify API token, but it seems unavoidable at this point.

I had switched the primary dev target to ST a while back as they had working OAuth redirect, but I'm making a large push to get all of my stuff migrated to HE now that it's in a state where I can replace 99% of what ST does. Future versions will be HE focused, but will have a clunky OAuth setup which sort of bums me out a bit :-/

**Comment by turbodog** [comment]
Thanks Mitch. Happy to help test anything on ST. And if I could get a working install, a contribution I could make is documenting that.

**Comment by rvrolyk** [comment]
Happy to verify anything on HE as well.  Agreed it'd be nice if the OAuth redirect was handled but maybe it'll be there as the platform develops.

**Comment by mitchpond** [comment]
Master branch has been updated with working code. It's still a bit rough around the edges since I just discovered the changes to the OAuth system on Hubitat's side tonight and made some quick updates. I'm closing this issue as fixed :)
