### ISSUE TITLE
Value for getCallbackUrl?

### ISSUE THREAD

**Issue by crownrallyadam** [mitchpond/Spotify-HE-Connect#2]
Apologies if this isn't the right place to ask. I've gotten my clientId and clientSecret from Spotify for Developers, and filled them in in this app:
private getSpotifyClientId() { "{my_spotify_clientid}" }
private getSpotifyClientSecret() { "{my_spotify_client_secret}" }
private getCallbackUrl() { "https://cloud.hubitat.com/api/cffd7747-9fa5-4fd9-97c8-7de7027f4425/apps/113/oauth/callback?access_token=BQAAZupmnpjqzkGuQNr8rFLAK5Bi4TYiKAqTHW3Kzw_GmbZrL-q3-QaAiA_AZQ-p0wFpQur7fupYJfkYM28" }

I can't seem to figure out what the callback URL should be. If I click the "OAuth" button on the app this is what I see.
![image](https://user-images.githubusercontent.com/25123826/56914444-c4643780-6a79-11e9-8029-7e4f38697057.png)

**Comment by mitchpond** [comment]
I'll push what I have over lunch (sometime between 12 and 1 CDT). I'm rewriting a bunch of it to account for the sloppy OAuth process. It's not in a good state, but if you feel like hacking around with it, it might be of use.

**Comment by mitchpond** [comment]
https://github.com/mitchpond/Spotify-HE-Connect/tree/he-refactor

The app should give you the correct callback URL to provide to Spotify in the config pages.

**Comment by mitchpond** [comment]
The latest push to the master branch demonstrates the new OAuth flow. The code can be installed as-is without creating a developer account. At least until I start hitting API limits.
